---
# dataset related params
data:
  train_contract_dir: ../labeling/contracts/tagged/train
  eval_contract_dir: ../labeling/contracts/tagged/eval
  test_contract_dir: ../labeling/contracts/tagged/test

  label_list:
    - b_t
    - e_t
    - i_t
    - s_t
    - b_n
    - e_n
    - i_n
    - s_n
    - b_st
    - e_st
    - i_st
    - s_st
    - b_sn
    - e_sn
    - i_sn
    - s_sn
    - b_sst
    - e_sst
    - i_sst
    - s_sst
    - b_ssn
    - e_ssn
    - i_ssn
    - s_ssn
    - b_ssst
    - e_ssst
    - i_ssst
    - s_ssst
    - b_sssn
    - e_sssn
    - i_sssn
    - s_sssn
    - o

model:
  use_large_model: false
  train_batch_size: 16
  eval_batch_size: 2

  num_epochs: 10
  learning_rate: 5e-5

  # index to ignore in the loss_fn
  ignore_index: -100

  model_savepath: markuplm_model.pt

<<<<<<< HEAD
ablation:
  run_ablation: true
  is_shuffle_xpath_exp: false
  xpath_tag_pad_token: 216
  xpath_subs_pad_token: 1001
=======
  early_stop_patience: 2
>>>>>>> 9d6e56b51579d54fe9003bfe2cfee5b2cab0dd67


...
